sudo: true
dist: xenial 
services:
  - docker
language: python 
python:
  - "3.5"

before_install:
  - pip3 install cwltool
  - docker build -t umitrans .

script:
  # Both of these same tests, in Docker
  # Functional tests
  - docker run --entrypoint /umitrans/.travis/unit-test.sh umitrans
  # Unit tests
  - docker run --entrypoint /umitrans/functional_tests/umitrans-test.sh umitrans -p umitrans -d /umitrans/functional_tests/test_data -v

  # CWL definition test
  - cwltool umitrans.cwl --fasta_file functional_tests/test_data/two_sequence.fasta
